# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: install packages
    - run: npm ci
      working-directory: ./v1  
    - name: build app
    - run: npm run build
      working-directory: ./v1
    - name: test app
    - run: npm test
      working-directory: ./v1    
      env:
        CI: true


        - name: Clean temp directory
  run: rm -rf *
  working-directory: ./temp
